индексация

In [ ]:
import numpy as np
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
mask = [True, False] * 5
mask

[True, False, True, False, True, False, True, False, True, False]

In [ ]:
x = list(x)

In [ ]:
x = np.random.rand(3, 4, 5)

In [ ]:
x.shape

(3, 4, 5)

In [ ]:
x[..., 0, None].shape

(3, 4, 1)

mean, max, min

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.random.rand(4, 5, 6)

arange

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

np.random.shuffle

In [ ]:
np.zeros(30)[:, None]

In [ ]:
x = np.arange(10)
np.random.seed(0)
np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [ ]:
10 % 3

1